package com.tamanglhosantosh.bananagame.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
// This class was generated by chatgpt for login with the folder structure
/** The LoginRequest DTO is used to encapsulate the login credentials
 * (username and password) provided by the user.
 * Lombok's @Data annotation generates the necessary boilerplate code
 * like getters, setters, and constructors
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class LoginRequest {

    private String username; // Entered username or email
    private String password; // Entered password

}

